<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Rating_5_Stars</name>
   <tag></tag>
   <elementGuidId>00afef89-0e24-4812-a7ce-644e0df1d0a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#li_R5 > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='li_R5']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>R5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li_R5&quot;)/label[1]</value>
   </webElementProperties>
</WebElementEntity>
